load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "mock_service_lib",
    srcs = ["main.go"],
    importpath = "ck_remote_proxy/mock_service",
    visibility = ["//visibility:private"],
    deps = [
        "//protos",
        "@org_golang_google_grpc//:grpc",
    ],
)

go_binary(
    name = "mock_service",
    embed = [":mock_service_lib"],
    visibility = ["//visibility:public"],
)
