load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "stream_client_lib",
    srcs = ["main.go"],
    importpath = "ck_remote_proxy/tools/stream_client",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_clickhouse_ch_go//proto",
        "@com_github_clickhouse_clickhouse_go_v2//:clickhouse-go",
    ],
)

go_binary(
    name = "stream_client",
    embed = [":stream_client_lib"],
    visibility = ["//visibility:public"],
)
