load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")

go_library(
    name = "protos",
    embed = [":protos_go_proto"],
    importpath = "ck_remote_proxy/protos",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "protos_proto",
    srcs = ["rewriter.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "protos_go_proto",
    compilers = [
        "@rules_go//proto:go_proto",
        "@rules_go//proto:go_grpc_v2",
    ],
    importpath = "ck_remote_proxy/protos",
    proto = ":protos_proto",
    visibility = ["//visibility:public"],
)
