// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protos/rewriter.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewriteOp int32

const (
	RewriteOp_TableNameRewrite       RewriteOp = 0
	RewriteOp_LimitRewrite           RewriteOp = 1
	RewriteOp_OffsetRewrite          RewriteOp = 2
	RewriteOp_SettingsRewrite        RewriteOp = 3
	RewriteOp_CommonTableExprRewrite RewriteOp = 4
	RewriteOp_DatabaseNameRewrite    RewriteOp = 5
	RewriteOp_ShowTablesRewrite      RewriteOp = 6
)

// Enum value maps for RewriteOp.
var (
	RewriteOp_name = map[int32]string{
		0: "TableNameRewrite",
		1: "LimitRewrite",
		2: "OffsetRewrite",
		3: "SettingsRewrite",
		4: "CommonTableExprRewrite",
		5: "DatabaseNameRewrite",
		6: "ShowTablesRewrite",
	}
	RewriteOp_value = map[string]int32{
		"TableNameRewrite":       0,
		"LimitRewrite":           1,
		"OffsetRewrite":          2,
		"SettingsRewrite":        3,
		"CommonTableExprRewrite": 4,
		"DatabaseNameRewrite":    5,
		"ShowTablesRewrite":      6,
	}
)

func (x RewriteOp) Enum() *RewriteOp {
	p := new(RewriteOp)
	*p = x
	return p
}

func (x RewriteOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RewriteOp) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[0].Descriptor()
}

func (RewriteOp) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[0]
}

func (x RewriteOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RewriteOp.Descriptor instead.
func (RewriteOp) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{0}
}

type SettingType int32

const (
	SettingType_String SettingType = 0
	SettingType_Bool   SettingType = 1
	SettingType_Int    SettingType = 2
	SettingType_Uint64 SettingType = 3
)

// Enum value maps for SettingType.
var (
	SettingType_name = map[int32]string{
		0: "String",
		1: "Bool",
		2: "Int",
		3: "Uint64",
	}
	SettingType_value = map[string]int32{
		"String": 0,
		"Bool":   1,
		"Int":    2,
		"Uint64": 3,
	}
)

func (x SettingType) Enum() *SettingType {
	p := new(SettingType)
	*p = x
	return p
}

func (x SettingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettingType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[1].Descriptor()
}

func (SettingType) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[1]
}

func (x SettingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettingType.Descriptor instead.
func (SettingType) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{1}
}

type RewriteCode int32

const (
	RewriteCode_Success      RewriteCode = 0
	RewriteCode_SyntaxError  RewriteCode = 1
	RewriteCode_RewriteError RewriteCode = 2
)

// Enum value maps for RewriteCode.
var (
	RewriteCode_name = map[int32]string{
		0: "Success",
		1: "SyntaxError",
		2: "RewriteError",
	}
	RewriteCode_value = map[string]int32{
		"Success":      0,
		"SyntaxError":  1,
		"RewriteError": 2,
	}
)

func (x RewriteCode) Enum() *RewriteCode {
	p := new(RewriteCode)
	*p = x
	return p
}

func (x RewriteCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RewriteCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_rewriter_proto_enumTypes[2].Descriptor()
}

func (RewriteCode) Type() protoreflect.EnumType {
	return &file_protos_rewriter_proto_enumTypes[2]
}

func (x RewriteCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RewriteCode.Descriptor instead.
func (RewriteCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{2}
}

type RewriteTableNameArgs struct {
	state                protoimpl.MessageState                             `protogen:"open.v1"`
	TableMap             map[string]string                                  `protobuf:"bytes,1,rep,name=table_map,json=tableMap,proto3" json:"table_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemoteTableMap       map[string]*RewriteTableNameArgs_RemoteTable       `protobuf:"bytes,2,rep,name=remote_table_map,json=remoteTableMap,proto3" json:"remote_table_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TableWithDatabaseMap map[string]*RewriteTableNameArgs_TableWithDatabase `protobuf:"bytes,3,rep,name=table_with_database_map,json=tableWithDatabaseMap,proto3" json:"table_with_database_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RewriteTableNameArgs) Reset() {
	*x = RewriteTableNameArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableNameArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableNameArgs) ProtoMessage() {}

func (x *RewriteTableNameArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableNameArgs.ProtoReflect.Descriptor instead.
func (*RewriteTableNameArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{0}
}

func (x *RewriteTableNameArgs) GetTableMap() map[string]string {
	if x != nil {
		return x.TableMap
	}
	return nil
}

func (x *RewriteTableNameArgs) GetRemoteTableMap() map[string]*RewriteTableNameArgs_RemoteTable {
	if x != nil {
		return x.RemoteTableMap
	}
	return nil
}

func (x *RewriteTableNameArgs) GetTableWithDatabaseMap() map[string]*RewriteTableNameArgs_TableWithDatabase {
	if x != nil {
		return x.TableWithDatabaseMap
	}
	return nil
}

type RewriteLimitArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in protos/rewriter.proto.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*RewriteLimitArgs_ReplaceLimit_
	//	*RewriteLimitArgs_ForceLimit
	Value         isRewriteLimitArgs_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteLimitArgs) Reset() {
	*x = RewriteLimitArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteLimitArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteLimitArgs) ProtoMessage() {}

func (x *RewriteLimitArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteLimitArgs.ProtoReflect.Descriptor instead.
func (*RewriteLimitArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in protos/rewriter.proto.
func (x *RewriteLimitArgs) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RewriteLimitArgs) GetValue() isRewriteLimitArgs_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RewriteLimitArgs) GetReplaceLimit() *RewriteLimitArgs_ReplaceLimit {
	if x != nil {
		if x, ok := x.Value.(*RewriteLimitArgs_ReplaceLimit_); ok {
			return x.ReplaceLimit
		}
	}
	return nil
}

func (x *RewriteLimitArgs) GetForceLimit() int32 {
	if x != nil {
		if x, ok := x.Value.(*RewriteLimitArgs_ForceLimit); ok {
			return x.ForceLimit
		}
	}
	return 0
}

type isRewriteLimitArgs_Value interface {
	isRewriteLimitArgs_Value()
}

type RewriteLimitArgs_ReplaceLimit_ struct {
	ReplaceLimit *RewriteLimitArgs_ReplaceLimit `protobuf:"bytes,2,opt,name=replace_limit,json=replaceLimit,proto3,oneof"`
}

type RewriteLimitArgs_ForceLimit struct {
	ForceLimit int32 `protobuf:"varint,3,opt,name=force_limit,json=forceLimit,proto3,oneof"`
}

func (*RewriteLimitArgs_ReplaceLimit_) isRewriteLimitArgs_Value() {}

func (*RewriteLimitArgs_ForceLimit) isRewriteLimitArgs_Value() {}

type RewriteOffsetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteOffsetArgs) Reset() {
	*x = RewriteOffsetArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteOffsetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteOffsetArgs) ProtoMessage() {}

func (x *RewriteOffsetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteOffsetArgs.ProtoReflect.Descriptor instead.
func (*RewriteOffsetArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{2}
}

func (x *RewriteOffsetArgs) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type RewriteCommonTableExprArgs struct {
	state         protoimpl.MessageState                                 `protogen:"open.v1"`
	CteMap        map[string]*RewriteCommonTableExprArgs_CommonTableExpr `protobuf:"bytes,1,rep,name=cte_map,json=cteMap,proto3" json:"cte_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteCommonTableExprArgs) Reset() {
	*x = RewriteCommonTableExprArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteCommonTableExprArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteCommonTableExprArgs) ProtoMessage() {}

func (x *RewriteCommonTableExprArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteCommonTableExprArgs.ProtoReflect.Descriptor instead.
func (*RewriteCommonTableExprArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{3}
}

func (x *RewriteCommonTableExprArgs) GetCteMap() map[string]*RewriteCommonTableExprArgs_CommonTableExpr {
	if x != nil {
		return x.CteMap
	}
	return nil
}

// DatabaseNameRewrite rewrites USE <db> statements.
// Three branches evaluated in order:
//  1. database_map hit (processorID → physical): "USE <physical>"
//  2. known_physical_databases hit: leave SQL unchanged
//  3. default_database non-empty: "USE <default_database>",
//     response.matched_processor_id = <target>
type RewriteDatabaseNameArgs struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DatabaseMap            map[string]string      `protobuf:"bytes,1,rep,name=database_map,json=databaseMap,proto3" json:"database_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	KnownPhysicalDatabases []string               `protobuf:"bytes,2,rep,name=known_physical_databases,json=knownPhysicalDatabases,proto3" json:"known_physical_databases,omitempty"`
	DefaultDatabase        string                 `protobuf:"bytes,3,opt,name=default_database,json=defaultDatabase,proto3" json:"default_database,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RewriteDatabaseNameArgs) Reset() {
	*x = RewriteDatabaseNameArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteDatabaseNameArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteDatabaseNameArgs) ProtoMessage() {}

func (x *RewriteDatabaseNameArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteDatabaseNameArgs.ProtoReflect.Descriptor instead.
func (*RewriteDatabaseNameArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{4}
}

func (x *RewriteDatabaseNameArgs) GetDatabaseMap() map[string]string {
	if x != nil {
		return x.DatabaseMap
	}
	return nil
}

func (x *RewriteDatabaseNameArgs) GetKnownPhysicalDatabases() []string {
	if x != nil {
		return x.KnownPhysicalDatabases
	}
	return nil
}

func (x *RewriteDatabaseNameArgs) GetDefaultDatabase() string {
	if x != nil {
		return x.DefaultDatabase
	}
	return ""
}

// ShowTablesRewrite rewrites SHOW TABLES into a filtered SELECT.
// The server parses the AST's FROM/IN clause itself and resolves the target
// database + processor_id using the context below.
// Resolution order:
//
//	targetDB := FROM_clause > current_db > database (legacy)
//	empty targetDB             → empty-result sentinel SELECT
//	current_processor_id, if targetDB == current_db and SQL had no FROM
//	else db_processors[targetDB]
//	else                       → response.show_tables_passthrough = true
type RewriteShowTablesArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Legacy pre-resolved pair; new callers should leave these empty and fill
	// current_db + current_processor_id + db_processors instead.
	Database           string            `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	ProcessorId        string            `protobuf:"bytes,2,opt,name=processor_id,json=processorId,proto3" json:"processor_id,omitempty"`
	CurrentDb          string            `protobuf:"bytes,3,opt,name=current_db,json=currentDb,proto3" json:"current_db,omitempty"`
	CurrentProcessorId string            `protobuf:"bytes,4,opt,name=current_processor_id,json=currentProcessorId,proto3" json:"current_processor_id,omitempty"`
	DbProcessors       map[string]string `protobuf:"bytes,5,rep,name=db_processors,json=dbProcessors,proto3" json:"db_processors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // physicalDB → processorID
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RewriteShowTablesArgs) Reset() {
	*x = RewriteShowTablesArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteShowTablesArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteShowTablesArgs) ProtoMessage() {}

func (x *RewriteShowTablesArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteShowTablesArgs.ProtoReflect.Descriptor instead.
func (*RewriteShowTablesArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{5}
}

func (x *RewriteShowTablesArgs) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RewriteShowTablesArgs) GetProcessorId() string {
	if x != nil {
		return x.ProcessorId
	}
	return ""
}

func (x *RewriteShowTablesArgs) GetCurrentDb() string {
	if x != nil {
		return x.CurrentDb
	}
	return ""
}

func (x *RewriteShowTablesArgs) GetCurrentProcessorId() string {
	if x != nil {
		return x.CurrentProcessorId
	}
	return ""
}

func (x *RewriteShowTablesArgs) GetDbProcessors() map[string]string {
	if x != nil {
		return x.DbProcessors
	}
	return nil
}

type RewriteSettingsArgs struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Settings      []*RewriteSettingsArgs_Setting `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteSettingsArgs) Reset() {
	*x = RewriteSettingsArgs{}
	mi := &file_protos_rewriter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSettingsArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSettingsArgs) ProtoMessage() {}

func (x *RewriteSettingsArgs) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSettingsArgs.ProtoReflect.Descriptor instead.
func (*RewriteSettingsArgs) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{6}
}

func (x *RewriteSettingsArgs) GetSettings() []*RewriteSettingsArgs_Setting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type RewriteOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Op    RewriteOp              `protobuf:"varint,1,opt,name=op,proto3,enum=rewriter.RewriteOp" json:"op,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*RewriteOption_TableNameArgs
	//	*RewriteOption_LimitArgs
	//	*RewriteOption_OffsetArgs
	//	*RewriteOption_SettingsArgs
	//	*RewriteOption_CommonTableExprArgs
	//	*RewriteOption_DatabaseNameArgs
	//	*RewriteOption_ShowTablesArgs
	Value         isRewriteOption_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteOption) Reset() {
	*x = RewriteOption{}
	mi := &file_protos_rewriter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteOption) ProtoMessage() {}

func (x *RewriteOption) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteOption.ProtoReflect.Descriptor instead.
func (*RewriteOption) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{7}
}

func (x *RewriteOption) GetOp() RewriteOp {
	if x != nil {
		return x.Op
	}
	return RewriteOp_TableNameRewrite
}

func (x *RewriteOption) GetValue() isRewriteOption_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RewriteOption) GetTableNameArgs() *RewriteTableNameArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_TableNameArgs); ok {
			return x.TableNameArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetLimitArgs() *RewriteLimitArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_LimitArgs); ok {
			return x.LimitArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetOffsetArgs() *RewriteOffsetArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_OffsetArgs); ok {
			return x.OffsetArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetSettingsArgs() *RewriteSettingsArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_SettingsArgs); ok {
			return x.SettingsArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetCommonTableExprArgs() *RewriteCommonTableExprArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_CommonTableExprArgs); ok {
			return x.CommonTableExprArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetDatabaseNameArgs() *RewriteDatabaseNameArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_DatabaseNameArgs); ok {
			return x.DatabaseNameArgs
		}
	}
	return nil
}

func (x *RewriteOption) GetShowTablesArgs() *RewriteShowTablesArgs {
	if x != nil {
		if x, ok := x.Value.(*RewriteOption_ShowTablesArgs); ok {
			return x.ShowTablesArgs
		}
	}
	return nil
}

type isRewriteOption_Value interface {
	isRewriteOption_Value()
}

type RewriteOption_TableNameArgs struct {
	TableNameArgs *RewriteTableNameArgs `protobuf:"bytes,2,opt,name=table_name_args,json=tableNameArgs,proto3,oneof"`
}

type RewriteOption_LimitArgs struct {
	LimitArgs *RewriteLimitArgs `protobuf:"bytes,3,opt,name=limit_args,json=limitArgs,proto3,oneof"`
}

type RewriteOption_OffsetArgs struct {
	OffsetArgs *RewriteOffsetArgs `protobuf:"bytes,4,opt,name=offset_args,json=offsetArgs,proto3,oneof"`
}

type RewriteOption_SettingsArgs struct {
	SettingsArgs *RewriteSettingsArgs `protobuf:"bytes,5,opt,name=settings_args,json=settingsArgs,proto3,oneof"`
}

type RewriteOption_CommonTableExprArgs struct {
	CommonTableExprArgs *RewriteCommonTableExprArgs `protobuf:"bytes,6,opt,name=common_table_expr_args,json=commonTableExprArgs,proto3,oneof"`
}

type RewriteOption_DatabaseNameArgs struct {
	DatabaseNameArgs *RewriteDatabaseNameArgs `protobuf:"bytes,7,opt,name=database_name_args,json=databaseNameArgs,proto3,oneof"`
}

type RewriteOption_ShowTablesArgs struct {
	ShowTablesArgs *RewriteShowTablesArgs `protobuf:"bytes,8,opt,name=show_tables_args,json=showTablesArgs,proto3,oneof"`
}

func (*RewriteOption_TableNameArgs) isRewriteOption_Value() {}

func (*RewriteOption_LimitArgs) isRewriteOption_Value() {}

func (*RewriteOption_OffsetArgs) isRewriteOption_Value() {}

func (*RewriteOption_SettingsArgs) isRewriteOption_Value() {}

func (*RewriteOption_CommonTableExprArgs) isRewriteOption_Value() {}

func (*RewriteOption_DatabaseNameArgs) isRewriteOption_Value() {}

func (*RewriteOption_ShowTablesArgs) isRewriteOption_Value() {}

type RewriteSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Options       []*RewriteOption       `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteSQLRequest) Reset() {
	*x = RewriteSQLRequest{}
	mi := &file_protos_rewriter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSQLRequest) ProtoMessage() {}

func (x *RewriteSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSQLRequest.ProtoReflect.Descriptor instead.
func (*RewriteSQLRequest) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{8}
}

func (x *RewriteSQLRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *RewriteSQLRequest) GetOptions() []*RewriteOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type RewriteSQLResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Code                       RewriteCode            `protobuf:"varint,1,opt,name=code,proto3,enum=rewriter.RewriteCode" json:"code,omitempty"`
	Message                    string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SqlAfterRewrite            string                 `protobuf:"bytes,3,opt,name=sql_after_rewrite,json=sqlAfterRewrite,proto3" json:"sql_after_rewrite,omitempty"`
	OriginalAccessedTableNames []string               `protobuf:"bytes,4,rep,name=original_accessed_table_names,json=originalAccessedTableNames,proto3" json:"original_accessed_table_names,omitempty"`
	StatementType              string                 `protobuf:"bytes,5,opt,name=statement_type,json=statementType,proto3" json:"statement_type,omitempty"` // "SELECT", "USE", "SHOW_TABLES", etc.
	// USE DatabaseNameRewrite: original target when the default_database
	// fallback branch fired; caller tracks it as the connection's processor_id.
	MatchedProcessorId string `protobuf:"bytes,6,opt,name=matched_processor_id,json=matchedProcessorId,proto3" json:"matched_processor_id,omitempty"`
	// SHOW TABLES: true when the rewriter asks caller to pass original SQL
	// through (targetDB has no processor mapping and no processor context).
	ShowTablesPassthrough bool `protobuf:"varint,7,opt,name=show_tables_passthrough,json=showTablesPassthrough,proto3" json:"show_tables_passthrough,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RewriteSQLResponse) Reset() {
	*x = RewriteSQLResponse{}
	mi := &file_protos_rewriter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSQLResponse) ProtoMessage() {}

func (x *RewriteSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSQLResponse.ProtoReflect.Descriptor instead.
func (*RewriteSQLResponse) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{9}
}

func (x *RewriteSQLResponse) GetCode() RewriteCode {
	if x != nil {
		return x.Code
	}
	return RewriteCode_Success
}

func (x *RewriteSQLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RewriteSQLResponse) GetSqlAfterRewrite() string {
	if x != nil {
		return x.SqlAfterRewrite
	}
	return ""
}

func (x *RewriteSQLResponse) GetOriginalAccessedTableNames() []string {
	if x != nil {
		return x.OriginalAccessedTableNames
	}
	return nil
}

func (x *RewriteSQLResponse) GetStatementType() string {
	if x != nil {
		return x.StatementType
	}
	return ""
}

func (x *RewriteSQLResponse) GetMatchedProcessorId() string {
	if x != nil {
		return x.MatchedProcessorId
	}
	return ""
}

func (x *RewriteSQLResponse) GetShowTablesPassthrough() bool {
	if x != nil {
		return x.ShowTablesPassthrough
	}
	return false
}

type RewriteErrorMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Options       []*RewriteOption       `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteErrorMessageRequest) Reset() {
	*x = RewriteErrorMessageRequest{}
	mi := &file_protos_rewriter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteErrorMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteErrorMessageRequest) ProtoMessage() {}

func (x *RewriteErrorMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteErrorMessageRequest.ProtoReflect.Descriptor instead.
func (*RewriteErrorMessageRequest) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{10}
}

func (x *RewriteErrorMessageRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *RewriteErrorMessageRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RewriteErrorMessageRequest) GetOptions() []*RewriteOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type RewriteErrorMessageResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              RewriteCode            `protobuf:"varint,1,opt,name=code,proto3,enum=rewriter.RewriteCode" json:"code,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorAfterRewrite string                 `protobuf:"bytes,3,opt,name=error_after_rewrite,json=errorAfterRewrite,proto3" json:"error_after_rewrite,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RewriteErrorMessageResponse) Reset() {
	*x = RewriteErrorMessageResponse{}
	mi := &file_protos_rewriter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteErrorMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteErrorMessageResponse) ProtoMessage() {}

func (x *RewriteErrorMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteErrorMessageResponse.ProtoReflect.Descriptor instead.
func (*RewriteErrorMessageResponse) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{11}
}

func (x *RewriteErrorMessageResponse) GetCode() RewriteCode {
	if x != nil {
		return x.Code
	}
	return RewriteCode_Success
}

func (x *RewriteErrorMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RewriteErrorMessageResponse) GetErrorAfterRewrite() string {
	if x != nil {
		return x.ErrorAfterRewrite
	}
	return ""
}

type RewriteTableNameArgs_RemoteTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteTableNameArgs_RemoteTable) Reset() {
	*x = RewriteTableNameArgs_RemoteTable{}
	mi := &file_protos_rewriter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableNameArgs_RemoteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableNameArgs_RemoteTable) ProtoMessage() {}

func (x *RewriteTableNameArgs_RemoteTable) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableNameArgs_RemoteTable.ProtoReflect.Descriptor instead.
func (*RewriteTableNameArgs_RemoteTable) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RewriteTableNameArgs_RemoteTable) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RewriteTableNameArgs_RemoteTable) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RewriteTableNameArgs_RemoteTable) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RewriteTableNameArgs_RemoteTable) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RewriteTableNameArgs_RemoteTable) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RewriteTableNameArgs_TableWithDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteTableNameArgs_TableWithDatabase) Reset() {
	*x = RewriteTableNameArgs_TableWithDatabase{}
	mi := &file_protos_rewriter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteTableNameArgs_TableWithDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteTableNameArgs_TableWithDatabase) ProtoMessage() {}

func (x *RewriteTableNameArgs_TableWithDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteTableNameArgs_TableWithDatabase.ProtoReflect.Descriptor instead.
func (*RewriteTableNameArgs_TableWithDatabase) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RewriteTableNameArgs_TableWithDatabase) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *RewriteTableNameArgs_TableWithDatabase) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type RewriteLimitArgs_ReplaceLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     int32                  `protobuf:"varint,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
	ReplaceTo     int32                  `protobuf:"varint,2,opt,name=replace_to,json=replaceTo,proto3" json:"replace_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteLimitArgs_ReplaceLimit) Reset() {
	*x = RewriteLimitArgs_ReplaceLimit{}
	mi := &file_protos_rewriter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteLimitArgs_ReplaceLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteLimitArgs_ReplaceLimit) ProtoMessage() {}

func (x *RewriteLimitArgs_ReplaceLimit) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteLimitArgs_ReplaceLimit.ProtoReflect.Descriptor instead.
func (*RewriteLimitArgs_ReplaceLimit) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RewriteLimitArgs_ReplaceLimit) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *RewriteLimitArgs_ReplaceLimit) GetReplaceTo() int32 {
	if x != nil {
		return x.ReplaceTo
	}
	return 0
}

type RewriteCommonTableExprArgs_CommonTableExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) Reset() {
	*x = RewriteCommonTableExprArgs_CommonTableExpr{}
	mi := &file_protos_rewriter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteCommonTableExprArgs_CommonTableExpr) ProtoMessage() {}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteCommonTableExprArgs_CommonTableExpr.ProtoReflect.Descriptor instead.
func (*RewriteCommonTableExprArgs_CommonTableExpr) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *RewriteCommonTableExprArgs_CommonTableExpr) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type RewriteSettingsArgs_Setting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type  SettingType            `protobuf:"varint,2,opt,name=type,proto3,enum=rewriter.SettingType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*RewriteSettingsArgs_Setting_StringValue
	//	*RewriteSettingsArgs_Setting_BoolValue
	//	*RewriteSettingsArgs_Setting_IntValue
	//	*RewriteSettingsArgs_Setting_Uint64Value
	Value         isRewriteSettingsArgs_Setting_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewriteSettingsArgs_Setting) Reset() {
	*x = RewriteSettingsArgs_Setting{}
	mi := &file_protos_rewriter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewriteSettingsArgs_Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteSettingsArgs_Setting) ProtoMessage() {}

func (x *RewriteSettingsArgs_Setting) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rewriter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteSettingsArgs_Setting.ProtoReflect.Descriptor instead.
func (*RewriteSettingsArgs_Setting) Descriptor() ([]byte, []int) {
	return file_protos_rewriter_proto_rawDescGZIP(), []int{6, 0}
}

func (x *RewriteSettingsArgs_Setting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RewriteSettingsArgs_Setting) GetType() SettingType {
	if x != nil {
		return x.Type
	}
	return SettingType_String
}

func (x *RewriteSettingsArgs_Setting) GetValue() isRewriteSettingsArgs_Setting_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RewriteSettingsArgs_Setting) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *RewriteSettingsArgs_Setting) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *RewriteSettingsArgs_Setting) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *RewriteSettingsArgs_Setting) GetUint64Value() uint64 {
	if x != nil {
		if x, ok := x.Value.(*RewriteSettingsArgs_Setting_Uint64Value); ok {
			return x.Uint64Value
		}
	}
	return 0
}

type isRewriteSettingsArgs_Setting_Value interface {
	isRewriteSettingsArgs_Setting_Value()
}

type RewriteSettingsArgs_Setting_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type RewriteSettingsArgs_Setting_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type RewriteSettingsArgs_Setting_IntValue struct {
	IntValue int32 `protobuf:"varint,5,opt,name=int_value,json=intValue,proto3,oneof"`
}

type RewriteSettingsArgs_Setting_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3,oneof"`
}

func (*RewriteSettingsArgs_Setting_StringValue) isRewriteSettingsArgs_Setting_Value() {}

func (*RewriteSettingsArgs_Setting_BoolValue) isRewriteSettingsArgs_Setting_Value() {}

func (*RewriteSettingsArgs_Setting_IntValue) isRewriteSettingsArgs_Setting_Value() {}

func (*RewriteSettingsArgs_Setting_Uint64Value) isRewriteSettingsArgs_Setting_Value() {}

var File_protos_rewriter_proto protoreflect.FileDescriptor

const file_protos_rewriter_proto_rawDesc = "" +
	"\n" +
	"\x15protos/rewriter.proto\x12\brewriter\"\xa4\x06\n" +
	"\x14RewriteTableNameArgs\x12I\n" +
	"\ttable_map\x18\x01 \x03(\v2,.rewriter.RewriteTableNameArgs.TableMapEntryR\btableMap\x12\\\n" +
	"\x10remote_table_map\x18\x02 \x03(\v22.rewriter.RewriteTableNameArgs.RemoteTableMapEntryR\x0eremoteTableMap\x12o\n" +
	"\x17table_with_database_map\x18\x03 \x03(\v28.rewriter.RewriteTableNameArgs.TableWithDatabaseMapEntryR\x14tableWithDatabaseMap\x1a\x83\x01\n" +
	"\vRemoteTable\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x1aE\n" +
	"\x11TableWithDatabase\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x1a;\n" +
	"\rTableMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1am\n" +
	"\x13RemoteTableMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12@\n" +
	"\x05value\x18\x02 \x01(\v2*.rewriter.RewriteTableNameArgs.RemoteTableR\x05value:\x028\x01\x1ay\n" +
	"\x19TableWithDatabaseMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.rewriter.RewriteTableNameArgs.TableWithDatabaseR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x10RewriteLimitArgs\x12\x18\n" +
	"\x05limit\x18\x01 \x01(\x05B\x02\x18\x01R\x05limit\x12N\n" +
	"\rreplace_limit\x18\x02 \x01(\v2'.rewriter.RewriteLimitArgs.ReplaceLimitH\x00R\freplaceLimit\x12!\n" +
	"\vforce_limit\x18\x03 \x01(\x05H\x00R\n" +
	"forceLimit\x1aK\n" +
	"\fReplaceLimit\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\x05R\tthreshold\x12\x1d\n" +
	"\n" +
	"replace_to\x18\x02 \x01(\x05R\treplaceToB\a\n" +
	"\x05value\"+\n" +
	"\x11RewriteOffsetArgs\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\"\x93\x02\n" +
	"\x1aRewriteCommonTableExprArgs\x12I\n" +
	"\acte_map\x18\x01 \x03(\v20.rewriter.RewriteCommonTableExprArgs.CteMapEntryR\x06cteMap\x1a9\n" +
	"\x0fCommonTableExpr\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x1ao\n" +
	"\vCteMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12J\n" +
	"\x05value\x18\x02 \x01(\v24.rewriter.RewriteCommonTableExprArgs.CommonTableExprR\x05value:\x028\x01\"\x95\x02\n" +
	"\x17RewriteDatabaseNameArgs\x12U\n" +
	"\fdatabase_map\x18\x01 \x03(\v22.rewriter.RewriteDatabaseNameArgs.DatabaseMapEntryR\vdatabaseMap\x128\n" +
	"\x18known_physical_databases\x18\x02 \x03(\tR\x16knownPhysicalDatabases\x12)\n" +
	"\x10default_database\x18\x03 \x01(\tR\x0fdefaultDatabase\x1a>\n" +
	"\x10DatabaseMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x02\n" +
	"\x15RewriteShowTablesArgs\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12!\n" +
	"\fprocessor_id\x18\x02 \x01(\tR\vprocessorId\x12\x1d\n" +
	"\n" +
	"current_db\x18\x03 \x01(\tR\tcurrentDb\x120\n" +
	"\x14current_processor_id\x18\x04 \x01(\tR\x12currentProcessorId\x12V\n" +
	"\rdb_processors\x18\x05 \x03(\v21.rewriter.RewriteShowTablesArgs.DbProcessorsEntryR\fdbProcessors\x1a?\n" +
	"\x11DbProcessorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x02\n" +
	"\x13RewriteSettingsArgs\x12A\n" +
	"\bsettings\x18\x01 \x03(\v2%.rewriter.RewriteSettingsArgs.SettingR\bsettings\x1a\xd9\x01\n" +
	"\aSetting\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.rewriter.SettingTypeR\x04type\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x05 \x01(\x05H\x00R\bintValue\x12#\n" +
	"\fuint64_value\x18\x06 \x01(\x04H\x00R\vuint64ValueB\a\n" +
	"\x05value\"\xc7\x04\n" +
	"\rRewriteOption\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.rewriter.RewriteOpR\x02op\x12H\n" +
	"\x0ftable_name_args\x18\x02 \x01(\v2\x1e.rewriter.RewriteTableNameArgsH\x00R\rtableNameArgs\x12;\n" +
	"\n" +
	"limit_args\x18\x03 \x01(\v2\x1a.rewriter.RewriteLimitArgsH\x00R\tlimitArgs\x12>\n" +
	"\voffset_args\x18\x04 \x01(\v2\x1b.rewriter.RewriteOffsetArgsH\x00R\n" +
	"offsetArgs\x12D\n" +
	"\rsettings_args\x18\x05 \x01(\v2\x1d.rewriter.RewriteSettingsArgsH\x00R\fsettingsArgs\x12[\n" +
	"\x16common_table_expr_args\x18\x06 \x01(\v2$.rewriter.RewriteCommonTableExprArgsH\x00R\x13commonTableExprArgs\x12Q\n" +
	"\x12database_name_args\x18\a \x01(\v2!.rewriter.RewriteDatabaseNameArgsH\x00R\x10databaseNameArgs\x12K\n" +
	"\x10show_tables_args\x18\b \x01(\v2\x1f.rewriter.RewriteShowTablesArgsH\x00R\x0eshowTablesArgsB\a\n" +
	"\x05value\"X\n" +
	"\x11RewriteSQLRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x121\n" +
	"\aoptions\x18\x02 \x03(\v2\x17.rewriter.RewriteOptionR\aoptions\"\xd9\x02\n" +
	"\x12RewriteSQLResponse\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.rewriter.RewriteCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x11sql_after_rewrite\x18\x03 \x01(\tR\x0fsqlAfterRewrite\x12A\n" +
	"\x1doriginal_accessed_table_names\x18\x04 \x03(\tR\x1aoriginalAccessedTableNames\x12%\n" +
	"\x0estatement_type\x18\x05 \x01(\tR\rstatementType\x120\n" +
	"\x14matched_processor_id\x18\x06 \x01(\tR\x12matchedProcessorId\x126\n" +
	"\x17show_tables_passthrough\x18\a \x01(\bR\x15showTablesPassthrough\"\x86\x01\n" +
	"\x1aRewriteErrorMessageRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x121\n" +
	"\aoptions\x18\x03 \x03(\v2\x17.rewriter.RewriteOptionR\aoptions\"\x92\x01\n" +
	"\x1bRewriteErrorMessageResponse\x12)\n" +
	"\x04code\x18\x01 \x01(\x0e2\x15.rewriter.RewriteCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x13error_after_rewrite\x18\x03 \x01(\tR\x11errorAfterRewrite*\xa7\x01\n" +
	"\tRewriteOp\x12\x14\n" +
	"\x10TableNameRewrite\x10\x00\x12\x10\n" +
	"\fLimitRewrite\x10\x01\x12\x11\n" +
	"\rOffsetRewrite\x10\x02\x12\x13\n" +
	"\x0fSettingsRewrite\x10\x03\x12\x1a\n" +
	"\x16CommonTableExprRewrite\x10\x04\x12\x17\n" +
	"\x13DatabaseNameRewrite\x10\x05\x12\x15\n" +
	"\x11ShowTablesRewrite\x10\x06*8\n" +
	"\vSettingType\x12\n" +
	"\n" +
	"\x06String\x10\x00\x12\b\n" +
	"\x04Bool\x10\x01\x12\a\n" +
	"\x03Int\x10\x02\x12\n" +
	"\n" +
	"\x06Uint64\x10\x03*=\n" +
	"\vRewriteCode\x12\v\n" +
	"\aSuccess\x10\x00\x12\x0f\n" +
	"\vSyntaxError\x10\x01\x12\x10\n" +
	"\fRewriteError\x10\x022\xbf\x01\n" +
	"\x0fRewriterService\x12F\n" +
	"\aRewrite\x12\x1b.rewriter.RewriteSQLRequest\x1a\x1c.rewriter.RewriteSQLResponse\"\x00\x12d\n" +
	"\x13RewriteErrorMessage\x12$.rewriter.RewriteErrorMessageRequest\x1a%.rewriter.RewriteErrorMessageResponse\"\x00B.Z,github.com/sentioxyz/clickhouse-proxy/protosb\x06proto3"

var (
	file_protos_rewriter_proto_rawDescOnce sync.Once
	file_protos_rewriter_proto_rawDescData []byte
)

func file_protos_rewriter_proto_rawDescGZIP() []byte {
	file_protos_rewriter_proto_rawDescOnce.Do(func() {
		file_protos_rewriter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_rewriter_proto_rawDesc), len(file_protos_rewriter_proto_rawDesc)))
	})
	return file_protos_rewriter_proto_rawDescData
}

var file_protos_rewriter_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protos_rewriter_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protos_rewriter_proto_goTypes = []any{
	(RewriteOp)(0),                                 // 0: rewriter.RewriteOp
	(SettingType)(0),                               // 1: rewriter.SettingType
	(RewriteCode)(0),                               // 2: rewriter.RewriteCode
	(*RewriteTableNameArgs)(nil),                   // 3: rewriter.RewriteTableNameArgs
	(*RewriteLimitArgs)(nil),                       // 4: rewriter.RewriteLimitArgs
	(*RewriteOffsetArgs)(nil),                      // 5: rewriter.RewriteOffsetArgs
	(*RewriteCommonTableExprArgs)(nil),             // 6: rewriter.RewriteCommonTableExprArgs
	(*RewriteDatabaseNameArgs)(nil),                // 7: rewriter.RewriteDatabaseNameArgs
	(*RewriteShowTablesArgs)(nil),                  // 8: rewriter.RewriteShowTablesArgs
	(*RewriteSettingsArgs)(nil),                    // 9: rewriter.RewriteSettingsArgs
	(*RewriteOption)(nil),                          // 10: rewriter.RewriteOption
	(*RewriteSQLRequest)(nil),                      // 11: rewriter.RewriteSQLRequest
	(*RewriteSQLResponse)(nil),                     // 12: rewriter.RewriteSQLResponse
	(*RewriteErrorMessageRequest)(nil),             // 13: rewriter.RewriteErrorMessageRequest
	(*RewriteErrorMessageResponse)(nil),            // 14: rewriter.RewriteErrorMessageResponse
	(*RewriteTableNameArgs_RemoteTable)(nil),       // 15: rewriter.RewriteTableNameArgs.RemoteTable
	(*RewriteTableNameArgs_TableWithDatabase)(nil), // 16: rewriter.RewriteTableNameArgs.TableWithDatabase
	nil,                                   // 17: rewriter.RewriteTableNameArgs.TableMapEntry
	nil,                                   // 18: rewriter.RewriteTableNameArgs.RemoteTableMapEntry
	nil,                                   // 19: rewriter.RewriteTableNameArgs.TableWithDatabaseMapEntry
	(*RewriteLimitArgs_ReplaceLimit)(nil), // 20: rewriter.RewriteLimitArgs.ReplaceLimit
	(*RewriteCommonTableExprArgs_CommonTableExpr)(nil), // 21: rewriter.RewriteCommonTableExprArgs.CommonTableExpr
	nil,                                 // 22: rewriter.RewriteCommonTableExprArgs.CteMapEntry
	nil,                                 // 23: rewriter.RewriteDatabaseNameArgs.DatabaseMapEntry
	nil,                                 // 24: rewriter.RewriteShowTablesArgs.DbProcessorsEntry
	(*RewriteSettingsArgs_Setting)(nil), // 25: rewriter.RewriteSettingsArgs.Setting
}
var file_protos_rewriter_proto_depIdxs = []int32{
	17, // 0: rewriter.RewriteTableNameArgs.table_map:type_name -> rewriter.RewriteTableNameArgs.TableMapEntry
	18, // 1: rewriter.RewriteTableNameArgs.remote_table_map:type_name -> rewriter.RewriteTableNameArgs.RemoteTableMapEntry
	19, // 2: rewriter.RewriteTableNameArgs.table_with_database_map:type_name -> rewriter.RewriteTableNameArgs.TableWithDatabaseMapEntry
	20, // 3: rewriter.RewriteLimitArgs.replace_limit:type_name -> rewriter.RewriteLimitArgs.ReplaceLimit
	22, // 4: rewriter.RewriteCommonTableExprArgs.cte_map:type_name -> rewriter.RewriteCommonTableExprArgs.CteMapEntry
	23, // 5: rewriter.RewriteDatabaseNameArgs.database_map:type_name -> rewriter.RewriteDatabaseNameArgs.DatabaseMapEntry
	24, // 6: rewriter.RewriteShowTablesArgs.db_processors:type_name -> rewriter.RewriteShowTablesArgs.DbProcessorsEntry
	25, // 7: rewriter.RewriteSettingsArgs.settings:type_name -> rewriter.RewriteSettingsArgs.Setting
	0,  // 8: rewriter.RewriteOption.op:type_name -> rewriter.RewriteOp
	3,  // 9: rewriter.RewriteOption.table_name_args:type_name -> rewriter.RewriteTableNameArgs
	4,  // 10: rewriter.RewriteOption.limit_args:type_name -> rewriter.RewriteLimitArgs
	5,  // 11: rewriter.RewriteOption.offset_args:type_name -> rewriter.RewriteOffsetArgs
	9,  // 12: rewriter.RewriteOption.settings_args:type_name -> rewriter.RewriteSettingsArgs
	6,  // 13: rewriter.RewriteOption.common_table_expr_args:type_name -> rewriter.RewriteCommonTableExprArgs
	7,  // 14: rewriter.RewriteOption.database_name_args:type_name -> rewriter.RewriteDatabaseNameArgs
	8,  // 15: rewriter.RewriteOption.show_tables_args:type_name -> rewriter.RewriteShowTablesArgs
	10, // 16: rewriter.RewriteSQLRequest.options:type_name -> rewriter.RewriteOption
	2,  // 17: rewriter.RewriteSQLResponse.code:type_name -> rewriter.RewriteCode
	10, // 18: rewriter.RewriteErrorMessageRequest.options:type_name -> rewriter.RewriteOption
	2,  // 19: rewriter.RewriteErrorMessageResponse.code:type_name -> rewriter.RewriteCode
	15, // 20: rewriter.RewriteTableNameArgs.RemoteTableMapEntry.value:type_name -> rewriter.RewriteTableNameArgs.RemoteTable
	16, // 21: rewriter.RewriteTableNameArgs.TableWithDatabaseMapEntry.value:type_name -> rewriter.RewriteTableNameArgs.TableWithDatabase
	21, // 22: rewriter.RewriteCommonTableExprArgs.CteMapEntry.value:type_name -> rewriter.RewriteCommonTableExprArgs.CommonTableExpr
	1,  // 23: rewriter.RewriteSettingsArgs.Setting.type:type_name -> rewriter.SettingType
	11, // 24: rewriter.RewriterService.Rewrite:input_type -> rewriter.RewriteSQLRequest
	13, // 25: rewriter.RewriterService.RewriteErrorMessage:input_type -> rewriter.RewriteErrorMessageRequest
	12, // 26: rewriter.RewriterService.Rewrite:output_type -> rewriter.RewriteSQLResponse
	14, // 27: rewriter.RewriterService.RewriteErrorMessage:output_type -> rewriter.RewriteErrorMessageResponse
	26, // [26:28] is the sub-list for method output_type
	24, // [24:26] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_protos_rewriter_proto_init() }
func file_protos_rewriter_proto_init() {
	if File_protos_rewriter_proto != nil {
		return
	}
	file_protos_rewriter_proto_msgTypes[1].OneofWrappers = []any{
		(*RewriteLimitArgs_ReplaceLimit_)(nil),
		(*RewriteLimitArgs_ForceLimit)(nil),
	}
	file_protos_rewriter_proto_msgTypes[7].OneofWrappers = []any{
		(*RewriteOption_TableNameArgs)(nil),
		(*RewriteOption_LimitArgs)(nil),
		(*RewriteOption_OffsetArgs)(nil),
		(*RewriteOption_SettingsArgs)(nil),
		(*RewriteOption_CommonTableExprArgs)(nil),
		(*RewriteOption_DatabaseNameArgs)(nil),
		(*RewriteOption_ShowTablesArgs)(nil),
	}
	file_protos_rewriter_proto_msgTypes[22].OneofWrappers = []any{
		(*RewriteSettingsArgs_Setting_StringValue)(nil),
		(*RewriteSettingsArgs_Setting_BoolValue)(nil),
		(*RewriteSettingsArgs_Setting_IntValue)(nil),
		(*RewriteSettingsArgs_Setting_Uint64Value)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_rewriter_proto_rawDesc), len(file_protos_rewriter_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_rewriter_proto_goTypes,
		DependencyIndexes: file_protos_rewriter_proto_depIdxs,
		EnumInfos:         file_protos_rewriter_proto_enumTypes,
		MessageInfos:      file_protos_rewriter_proto_msgTypes,
	}.Build()
	File_protos_rewriter_proto = out.File
	file_protos_rewriter_proto_goTypes = nil
	file_protos_rewriter_proto_depIdxs = nil
}
