load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "proxy",
    srcs = [
        "chunked.go",
        "config.go",
        "observer.go",
        "proxy.go",
        "query_codec.go",
        "rewriter.go",
        "validator.go",
    ],
    importpath = "ck_remote_proxy/pkg/proxy",
    visibility = ["//visibility:public"],
    deps = [
        "//protos",
        "@com_github_clickhouse_ch_go//proto",
        "@com_github_ethereum_go_ethereum//crypto",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@com_github_segmentio_asm//bswap",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@in_yaml_go_yaml_v3//:yaml",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_grpc//keepalive",
        "@org_golang_x_crypto//sha3",
        "@sentio-core//common/log",
    ],
)

go_test(
    name = "proxy_test",
    srcs = glob(["*_test.go"]),
    embed = [":proxy"],
    data = [
        "rewriter_test_config.json",
        "rewriter_test_state.yaml",
    ],
    deps = [
        "@com_github_clickhouse_ch_go//proto",
        "@com_github_clickhouse_clickhouse_go_v2//lib/proto",
    ],
)
