load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "mock_server_lib",
    srcs = ["main.go"],
    importpath = "github.com/sentioxyz/clickhouse-proxy/tools/mock_server",
    visibility = ["//visibility:private"],
    deps = ["@com_github_clickhouse_ch_go//proto"],
)

go_binary(
    name = "mock_server",
    embed = [":mock_server_lib"],
    visibility = ["//visibility:public"],
)
