load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "proxy_lib",
    srcs = ["main.go"],
    importpath = "ck_remote_proxy/cmd/proxy",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/cluster",
        "//pkg/proxy",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@sentioxyz_sentio_core//common/clickhousemanager",
        "@sentioxyz_sentio_core//common/log",
        "@sentioxyz_sentio_core//network/sqlrewriter",
    ],
)

go_binary(
    name = "clickhouse-proxy",
    embed = [":proxy_lib"],
    visibility = ["//visibility:public"],
)
