load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cluster",
    srcs = [
        "health.go",
        "manager.go",
        "pool.go",
        "router.go",
        "types.go",
    ],
    importpath = "github.com/sentioxyz/clickhouse-proxy/pkg/cluster",
    visibility = ["//visibility:public"],
    deps = [
        "@sentioxyz_sentio_core//common/log",
    ],
)
